### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by smdnetau** [justonestep/processwire-instagramfeed#1]
Miniscule typo here:

```
<div class="instagram>
```

**Comment by justb3a** [comment]
I can not find this typo.

![instagram](https://cloud.githubusercontent.com/assets/4669205/10239361/7d5a0f3e-68cc-11e5-86aa-55c4b1e18fe4.png)

But I found this spelling mistakes yesterday in my client project while writing CSS (class ".instagram" did not match). Strange.

**Comment by smdnetau** [comment]
Sorry I should have said it was missing the closing " in the code examples :)

**Comment by justb3a** [comment]
ahh :laughing:  Because of the other mistake in the client project (copy - past ...) I didn't see this. I'll fix it (but I prefer to add a hotfix). Thanks a lot.
