### ISSUE TITLE
Authorization request needs scope "public_content"

### ISSUE THREAD

**Issue by wanze** [justonestep/processwire-instagramfeed#5]
Thanks for this module :) I had some problems that the generated access token did not include the scope `public_content` which now needs to be granted in order to get a user-ID or media items. Without it, there was an error message returned from the instagram API:
```
{u'meta': {u'code': 400, u'error_type':u'OAuthPermissionsException',
u'error_message': u'This request requires scope=public_content, but this
access token is not authorized with this scope. The user must re-authorize
your application with scope=public_content to be granted this permissions.'}}
```

**Solution**

Add a scope parameter to the authorization request in `InstagramFeed:getCode()`
```php
      $request = array(
        'client_id' => $this->clientId,
        'redirect_uri' => $redirect,
        'response_type' => 'code',
        'scope' => 'public_content', // <-- Add this scope
      );
```

Another small thingy: I think the `getRecentMedia` does not work correctly if you do not supply a username. I guess if you do NOT pass a username, it should fallback to the username of the module config. The logic is inverted atm :)
```php
  public function getRecentMedia($username = '') {
    if (!$username) $this->username = $username;
    // The above line needs to be:
   if ($username) $this->username = $username;
```

Cheers

**Comment by justb3a** [comment]
Thanks! Both issues have been fixed.
